import { getIndustryConfig, type IndustryId } from "@/config/industries";
import type { Campaign, Competitor, Keyword, NewsArticle, Publication, Trend } from "@/types";

const now = new Date("2026-09-06T00:00:00.000Z");
const isoDaysAgo = (days: number) =>
  new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

const trendSeeds: Trend[] = [
  {
    id: "trend-brazil-gambling-regulation",
    title: "Brazil Gambling Regulation",
    description: "New compliance and licensing changes affecting operators and affiliates.",
    industry: "igaming",
    category: "gambling-regulation",
    country: "Brazil",
    search_momentum: 94,
    news_momentum: 88,
    social_momentum: 61,
    competitor_coverage: 24,
    trend_stage: "ACCELERATING",
    detected_at: isoDaysAgo(3),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-ai-sports-betting",
    title: "AI Sports Betting",
    description: "AI-assisted wagering personalization, odds modeling, and risk controls.",
    industry: "igaming",
    category: "sports-betting",
    country: "United Kingdom",
    search_momentum: 78,
    news_momentum: 64,
    social_momentum: 72,
    competitor_coverage: 41,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(5),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-responsible-gambling-ux",
    title: "Responsible Gambling UX",
    description: "Safer play tooling and retention-friendly compliance UX patterns.",
    industry: "igaming",
    category: "responsible-gambling",
    country: "Malta",
    search_momentum: 71,
    news_momentum: 57,
    social_momentum: 48,
    competitor_coverage: 28,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(6),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-crypto-payments-igaming",
    title: "Crypto Payments in iGaming",
    description: "Player demand for fast settlement and alternative payment rails.",
    industry: "igaming",
    category: "payments",
    country: "Curacao",
    search_momentum: 82,
    news_momentum: 51,
    social_momentum: 67,
    competitor_coverage: 33,
    trend_stage: "ACCELERATING",
    detected_at: isoDaysAgo(4),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-esports-betting-summer",
    title: "Esports Betting Summer Surge",
    description: "Tournament schedules and creator coverage driving betting interest.",
    industry: "igaming",
    category: "esports",
    country: "Poland",
    search_momentum: 69,
    news_momentum: 43,
    social_momentum: 74,
    competitor_coverage: 38,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(8),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-online-casino-bonuses",
    title: "Online Casino Bonus Changes",
    description: "Promotional design and bonus terms shifting under regulation pressure.",
    industry: "igaming",
    category: "online-casino",
    country: "Canada",
    search_momentum: 74,
    news_momentum: 49,
    social_momentum: 45,
    competitor_coverage: 52,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(11),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-ai-code-assistants",
    title: "AI Code Assistants",
    description: "Developer tooling demand remains elevated across enterprise teams.",
    industry: "technology",
    category: "developer-tools",
    country: "United States",
    search_momentum: 89,
    news_momentum: 71,
    social_momentum: 78,
    competitor_coverage: 56,
    trend_stage: "ACCELERATING",
    detected_at: isoDaysAgo(4),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-saas-security-posture",
    title: "SaaS Security Posture",
    description: "Buyers are prioritizing compliance, auditability, and risk controls.",
    industry: "technology",
    category: "cybersecurity",
    country: "United States",
    search_momentum: 67,
    news_momentum: 62,
    social_momentum: 39,
    competitor_coverage: 47,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(7),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-cloud-cost-optimization",
    title: "Cloud Cost Optimization",
    description: "FinOps messaging and engineering-led cost control content are rising.",
    industry: "technology",
    category: "cloud",
    country: "United Kingdom",
    search_momentum: 61,
    news_momentum: 44,
    social_momentum: 36,
    competitor_coverage: 35,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(10),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-ev-infrastructure",
    title: "EV Charging Infrastructure",
    description: "Infrastructure rollout and regulation are shaping regional demand.",
    industry: "automotive",
    category: "ev",
    country: "Germany",
    search_momentum: 76,
    news_momentum: 66,
    social_momentum: 42,
    competitor_coverage: 31,
    trend_stage: "ACCELERATING",
    detected_at: isoDaysAgo(6),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-autonomous-driving-safety",
    title: "Autonomous Driving Safety",
    description: "Safety validation, regulation, and public trust are driving coverage.",
    industry: "automotive",
    category: "autonomous-vehicles",
    country: "Japan",
    search_momentum: 58,
    news_momentum: 55,
    social_momentum: 28,
    competitor_coverage: 22,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(9),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-vehicle-software",
    title: "Vehicle Software Updates",
    description: "Over-the-air software, safety recalls, and connected features are in focus.",
    industry: "automotive",
    category: "automotive-tech",
    country: "United States",
    search_momentum: 64,
    news_momentum: 52,
    social_momentum: 33,
    competitor_coverage: 29,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(12),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-payments-fraud-controls",
    title: "Payments Fraud Controls",
    description: "Fraud tooling, chargeback policy, and checkout trust messaging are rising.",
    industry: "finance",
    category: "payments",
    country: "United States",
    search_momentum: 73,
    news_momentum: 59,
    social_momentum: 34,
    competitor_coverage: 27,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(8),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-open-banking",
    title: "Open Banking APIs",
    description: "Financial data portability and partner integration are driving coverage.",
    industry: "finance",
    category: "banking",
    country: "United Kingdom",
    search_momentum: 66,
    news_momentum: 63,
    social_momentum: 31,
    competitor_coverage: 33,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(10),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-marketplace-conversion",
    title: "Marketplace Conversion",
    description: "E-commerce merchants are focusing on conversion rate and product discovery.",
    industry: "ecommerce",
    category: "conversion",
    country: "United States",
    search_momentum: 70,
    news_momentum: 48,
    social_momentum: 40,
    competitor_coverage: 39,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(7),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-retail-media",
    title: "Retail Media Networks",
    description: "Retail media spend and commerce SEO are converging.",
    industry: "ecommerce",
    category: "retail-tech",
    country: "United States",
    search_momentum: 62,
    news_momentum: 54,
    social_momentum: 29,
    competitor_coverage: 32,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(12),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-destination-demand",
    title: "Destination Demand",
    description: "Search interest in destinations is shifting by season and event calendars.",
    industry: "travel",
    category: "destinations",
    country: "Spain",
    search_momentum: 68,
    news_momentum: 41,
    social_momentum: 55,
    competitor_coverage: 25,
    trend_stage: "ACCELERATING",
    detected_at: isoDaysAgo(5),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-hospitality-pricing",
    title: "Hospitality Pricing",
    description: "Hotel pricing and revenue management updates are affecting content demand.",
    industry: "travel",
    category: "hospitality",
    country: "France",
    search_momentum: 59,
    news_momentum: 42,
    social_momentum: 26,
    competitor_coverage: 21,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(11),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-telehealth-ux",
    title: "Telehealth UX",
    description: "Patient acquisition and appointment flow optimization are in focus.",
    industry: "healthcare",
    category: "telehealth",
    country: "United States",
    search_momentum: 64,
    news_momentum: 58,
    social_momentum: 37,
    competitor_coverage: 30,
    trend_stage: "EMERGING",
    detected_at: isoDaysAgo(6),
    updated_at: isoDaysAgo(0),
  },
  {
    id: "trend-medtech-compliance",
    title: "MedTech Compliance",
    description: "Regulatory and quality assurance content is moving up the agenda.",
    industry: "healthcare",
    category: "medtech",
    country: "Germany",
    search_momentum: 57,
    news_momentum: 49,
    social_momentum: 22,
    competitor_coverage: 18,
    trend_stage: "NORMAL",
    detected_at: isoDaysAgo(9),
    updated_at: isoDaysAgo(0),
  },
];

const competitorSeeds: Competitor[] = [
  { id: "comp-1", name: "PlayArena", domain: "playarena.example", industry: "igaming", categories: ["sports-betting", "online-casino"], authority_score: 77, content_focus: ["odds updates", "bonus guides", "regulation"] },
  { id: "comp-2", name: "BetSignal", domain: "betsignal.example", industry: "igaming", categories: ["sports-betting", "esports"], authority_score: 73, content_focus: ["match previews", "betting tips", "promotions"] },
  { id: "comp-3", name: "SpinScope", domain: "spinscope.example", industry: "igaming", categories: ["online-casino", "payments"], authority_score: 69, content_focus: ["casino reviews", "wallets", "jurisdiction updates"] },
  { id: "comp-4", name: "CloudEdge", domain: "cloudedge.example", industry: "technology", categories: ["cloud", "saas"], authority_score: 81, content_focus: ["cloud optimization", "platform reviews"] },
  { id: "comp-5", name: "BytePilot", domain: "bytepilot.example", industry: "technology", categories: ["ai", "developer-tools"], authority_score: 84, content_focus: ["AI workflows", "developer tools"] },
  { id: "comp-6", name: "EV Route", domain: "evroute.example", industry: "automotive", categories: ["ev", "regulation"], authority_score: 68, content_focus: ["charging", "battery", "policy"] },
  { id: "comp-7", name: "DriveSignal", domain: "drivesignal.example", industry: "automotive", categories: ["autonomous-vehicles", "automotive-tech"], authority_score: 71, content_focus: ["ADAS", "software", "trust"] },
  { id: "comp-8", name: "FinPulse", domain: "finpulse.example", industry: "finance", categories: ["payments", "regulation"], authority_score: 79, content_focus: ["payments", "compliance"] },
  { id: "comp-9", name: "ShopSprint", domain: "shopsprint.example", industry: "ecommerce", categories: ["marketplaces", "conversion"], authority_score: 65, content_focus: ["conversion", "retail tech"] },
  { id: "comp-10", name: "TravelScope", domain: "travelscope.example", industry: "travel", categories: ["destinations", "hospitality"], authority_score: 63, content_focus: ["demand", "booking", "route planning"] },
];

const campaigns: Campaign[] = [
  {
    id: "campaign-1",
    title: "The State of Brazil's Online Gambling Market",
    industry: "igaming",
    trend_id: "trend-brazil-gambling-regulation",
    campaign_concept: "Data-driven analysis of regulation, consumer demand, and market readiness.",
    seo_targets: ["brazil gambling regulation", "online gambling brazil", "brazil sports betting"],
    pr_angle: "Market intelligence and compliance context for the new regulatory environment.",
    publication_targets: ["Gaming Insights Daily", "Regulatory Brief"],
    outreach_strategy: "Lead with a data point, then offer compliance commentary and local expert context.",
    created_at: isoDaysAgo(2),
    updated_at: isoDaysAgo(0),
  },
];

const buildKeywords = () => {
  const items: Keyword[] = [];
  const suffixes = ["guide", "report", "news", "statistics", "strategy", "analysis", "trends", "forecast"];
  for (let index = 0; index < 50; index += 1) {
    const trend = trendSeeds[index % trendSeeds.length];
    items.push({
      id: `kw-${index + 1}`,
      keyword: `${trend.title} ${suffixes[index % suffixes.length]}`,
      industry: trend.industry,
      category: trend.category,
      intent: ["INFORMATIONAL", "COMMERCIAL", "TRANSACTIONAL", "NAVIGATIONAL"][index % 4] as Keyword["intent"],
      search_volume: 2500 + index * 137,
      difficulty: 20 + (index * 3) % 60,
      freshness: 90 - (index % 25),
      cluster: `${trend.category}-cluster-${(index % 5) + 1}`,
    });
  }
  return items;
};

const buildNews = () => {
  const items: NewsArticle[] = [];
  const sourcePool = ["NewsWire", "Industry Pulse", "Market Daily", "Policy Watch", "Signal Desk"];
  const sentimentPool: NewsArticle["sentiment"][] = ["POSITIVE", "NEUTRAL", "NEGATIVE"];
  for (let index = 0; index < 30; index += 1) {
    const trend = trendSeeds[index % trendSeeds.length];
    items.push({
      id: `news-${index + 1}`,
      title: `${trend.title}: update ${index + 1}`,
      source: sourcePool[index % sourcePool.length],
      url: `https://news.example/articles/${index + 1}`,
      published_at: isoDaysAgo(index % 12),
      industry: trend.industry,
      country: trend.country,
      category: trend.category,
      topic: trend.title,
      sentiment: sentimentPool[index % sentimentPool.length],
      relevance: 55 + (index * 2) % 40,
    });
  }
  return items;
};

const buildPublications = () => {
  const items: Publication[] = [];
  const templateCategories = ["igaming", "technology", "automotive", "finance", "ecommerce", "travel"];
  for (let index = 0; index < 30; index += 1) {
    const category = templateCategories[index % templateCategories.length];
    items.push({
      id: `pub-${index + 1}`,
      name: `${category === "igaming" ? "Gaming" : category.charAt(0).toUpperCase() + category.slice(1)} Publication ${index + 1}`,
      domain: `${category}${index + 1}.example`,
      industry: category,
      country: ["United Kingdom", "United States", "Brazil", "Germany", "Canada"][index % 5],
      category,
      authority_score: 60 + (index * 2) % 30,
      industry_relevance: 55 + (index * 3) % 40,
      audience: `${category} audience ${index + 1}`,
      backlink_potential: 50 + (index * 4) % 40,
    });
  }
  return items;
};

export const DEMO_DATA = {
  trends: trendSeeds,
  keywords: buildKeywords(),
  newsArticles: buildNews(),
  competitors: competitorSeeds,
  publications: buildPublications(),
  campaigns,
} as const;

export const getDemoDataForIndustry = (industry: IndustryId | string) => {
  const normalized = getIndustryConfig(industry).id;
  return {
    trends: DEMO_DATA.trends.filter((trend) => trend.industry === normalized || normalized === "other"),
    keywords: DEMO_DATA.keywords.filter((keyword) => keyword.industry === normalized || normalized === "other"),
    newsArticles: DEMO_DATA.newsArticles.filter((article) => article.industry === normalized || normalized === "other"),
    competitors: DEMO_DATA.competitors.filter((competitor) => competitor.industry === normalized || normalized === "other"),
    publications: DEMO_DATA.publications.filter((publication) => publication.industry === normalized || normalized === "other"),
    campaigns: DEMO_DATA.campaigns.filter((campaign) => campaign.industry === normalized || normalized === "other"),
  };
};
