from __future__ import annotations

from datetime import datetime, timedelta, timezone

NOW = datetime(2026, 9, 6, tzinfo=timezone.utc)


def iso_days_ago(days: int) -> str:
    return (NOW - timedelta(days=days)).isoformat()


BASE_TRENDS = [
    {
        "id": "trend-brazil-gambling-regulation",
        "title": "Brazil Gambling Regulation",
        "description": "New compliance and licensing changes affecting operators and affiliates.",
        "industry": "igaming",
        "category": "gambling-regulation",
        "country": "Brazil",
        "search_momentum": 94,
        "news_momentum": 88,
        "social_momentum": 61,
        "competitor_coverage": 24,
        "trend_stage": "ACCELERATING",
        "detected_at": iso_days_ago(3),
        "updated_at": iso_days_ago(0),
    },
    {
        "id": "trend-ai-sports-betting",
        "title": "AI Sports Betting",
        "description": "AI-assisted wagering personalization, odds modeling, and risk controls.",
        "industry": "igaming",
        "category": "sports-betting",
        "country": "United Kingdom",
        "search_momentum": 78,
        "news_momentum": 64,
        "social_momentum": 72,
        "competitor_coverage": 41,
        "trend_stage": "EMERGING",
        "detected_at": iso_days_ago(5),
        "updated_at": iso_days_ago(0),
    },
    {
        "id": "trend-ev-infrastructure",
        "title": "EV Charging Infrastructure",
        "description": "Infrastructure rollout and regulation are shaping regional demand.",
        "industry": "automotive",
        "category": "ev",
        "country": "Germany",
        "search_momentum": 76,
        "news_momentum": 66,
        "social_momentum": 42,
        "competitor_coverage": 31,
        "trend_stage": "ACCELERATING",
        "detected_at": iso_days_ago(6),
        "updated_at": iso_days_ago(0),
    },
    {
        "id": "trend-ai-code-assistants",
        "title": "AI Code Assistants",
        "description": "Developer tooling demand remains elevated across enterprise teams.",
        "industry": "technology",
        "category": "developer-tools",
        "country": "United States",
        "search_momentum": 89,
        "news_momentum": 71,
        "social_momentum": 78,
        "competitor_coverage": 56,
        "trend_stage": "ACCELERATING",
        "detected_at": iso_days_ago(4),
        "updated_at": iso_days_ago(0),
    },
]


def build_demo_dataset():
    trend_pool = BASE_TRENDS + [
        {
            "id": "trend-responsible-gambling-ux",
            "title": "Responsible Gambling UX",
            "description": "Safer play tooling and retention-friendly compliance UX patterns.",
            "industry": "igaming",
            "category": "responsible-gambling",
            "country": "Malta",
            "search_momentum": 71,
            "news_momentum": 57,
            "social_momentum": 48,
            "competitor_coverage": 28,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(6),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-crypto-payments-igaming",
            "title": "Crypto Payments in iGaming",
            "description": "Player demand for fast settlement and alternative payment rails.",
            "industry": "igaming",
            "category": "payments",
            "country": "Curacao",
            "search_momentum": 82,
            "news_momentum": 51,
            "social_momentum": 67,
            "competitor_coverage": 33,
            "trend_stage": "ACCELERATING",
            "detected_at": iso_days_ago(4),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-esports-betting-summer",
            "title": "Esports Betting Summer Surge",
            "description": "Tournament schedules and creator coverage driving betting interest.",
            "industry": "igaming",
            "category": "esports",
            "country": "Poland",
            "search_momentum": 69,
            "news_momentum": 43,
            "social_momentum": 74,
            "competitor_coverage": 38,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(8),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-online-casino-bonuses",
            "title": "Online Casino Bonus Changes",
            "description": "Promotional design and bonus terms shifting under regulation pressure.",
            "industry": "igaming",
            "category": "online-casino",
            "country": "Canada",
            "search_momentum": 74,
            "news_momentum": 49,
            "social_momentum": 45,
            "competitor_coverage": 52,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(11),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-saas-security-posture",
            "title": "SaaS Security Posture",
            "description": "Buyers are prioritizing compliance, auditability, and risk controls.",
            "industry": "technology",
            "category": "cybersecurity",
            "country": "United States",
            "search_momentum": 67,
            "news_momentum": 62,
            "social_momentum": 39,
            "competitor_coverage": 47,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(7),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-cloud-cost-optimization",
            "title": "Cloud Cost Optimization",
            "description": "FinOps messaging and engineering-led cost control content are rising.",
            "industry": "technology",
            "category": "cloud",
            "country": "United Kingdom",
            "search_momentum": 61,
            "news_momentum": 44,
            "social_momentum": 36,
            "competitor_coverage": 35,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(10),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-autonomous-driving-safety",
            "title": "Autonomous Driving Safety",
            "description": "Safety validation, regulation, and public trust are driving coverage.",
            "industry": "automotive",
            "category": "autonomous-vehicles",
            "country": "Japan",
            "search_momentum": 58,
            "news_momentum": 55,
            "social_momentum": 28,
            "competitor_coverage": 22,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(9),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-payments-fraud-controls",
            "title": "Payments Fraud Controls",
            "description": "Fraud tooling, chargeback policy, and checkout trust messaging are rising.",
            "industry": "finance",
            "category": "payments",
            "country": "United States",
            "search_momentum": 73,
            "news_momentum": 59,
            "social_momentum": 34,
            "competitor_coverage": 27,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(8),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-open-banking",
            "title": "Open Banking APIs",
            "description": "Financial data portability and partner integration are driving coverage.",
            "industry": "finance",
            "category": "banking",
            "country": "United Kingdom",
            "search_momentum": 66,
            "news_momentum": 63,
            "social_momentum": 31,
            "competitor_coverage": 33,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(10),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-marketplace-conversion",
            "title": "Marketplace Conversion",
            "description": "E-commerce merchants are focusing on conversion rate and product discovery.",
            "industry": "ecommerce",
            "category": "conversion",
            "country": "United States",
            "search_momentum": 70,
            "news_momentum": 48,
            "social_momentum": 40,
            "competitor_coverage": 39,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(7),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-retail-media",
            "title": "Retail Media Networks",
            "description": "Retail media spend and commerce SEO are converging.",
            "industry": "ecommerce",
            "category": "retail-tech",
            "country": "United States",
            "search_momentum": 62,
            "news_momentum": 54,
            "social_momentum": 29,
            "competitor_coverage": 32,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(12),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-destination-demand",
            "title": "Destination Demand",
            "description": "Search interest in destinations is shifting by season and event calendars.",
            "industry": "travel",
            "category": "destinations",
            "country": "Spain",
            "search_momentum": 68,
            "news_momentum": 41,
            "social_momentum": 55,
            "competitor_coverage": 25,
            "trend_stage": "ACCELERATING",
            "detected_at": iso_days_ago(5),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-hospitality-pricing",
            "title": "Hospitality Pricing",
            "description": "Hotel pricing and revenue management updates are affecting content demand.",
            "industry": "travel",
            "category": "hospitality",
            "country": "France",
            "search_momentum": 59,
            "news_momentum": 42,
            "social_momentum": 26,
            "competitor_coverage": 21,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(11),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-telehealth-ux",
            "title": "Telehealth UX",
            "description": "Patient acquisition and appointment flow optimization are in focus.",
            "industry": "healthcare",
            "category": "telehealth",
            "country": "United States",
            "search_momentum": 64,
            "news_momentum": 58,
            "social_momentum": 37,
            "competitor_coverage": 30,
            "trend_stage": "EMERGING",
            "detected_at": iso_days_ago(6),
            "updated_at": iso_days_ago(0),
        },
        {
            "id": "trend-medtech-compliance",
            "title": "MedTech Compliance",
            "description": "Regulatory and quality assurance content is moving up the agenda.",
            "industry": "healthcare",
            "category": "medtech",
            "country": "Germany",
            "search_momentum": 57,
            "news_momentum": 49,
            "social_momentum": 22,
            "competitor_coverage": 18,
            "trend_stage": "NORMAL",
            "detected_at": iso_days_ago(9),
            "updated_at": iso_days_ago(0),
        },
    ]

    keywords = []
    suffixes = ["guide", "report", "news", "statistics", "strategy", "analysis", "trends", "forecast"]
    for index in range(50):
        trend = trend_pool[index % len(trend_pool)]
        keywords.append(
            {
                "id": f"kw-{index + 1}",
                "keyword": f"{trend['title']} {suffixes[index % len(suffixes)]}",
                "industry": trend["industry"],
                "category": trend["category"],
                "intent": ["INFORMATIONAL", "COMMERCIAL", "TRANSACTIONAL", "NAVIGATIONAL"][index % 4],
                "search_volume": 2500 + index * 137,
                "difficulty": 20 + (index * 3) % 60,
                "freshness": 90 - (index % 25),
                "cluster": f"{trend['category']}-cluster-{(index % 5) + 1}",
            }
        )

    news_articles = []
    source_pool = ["NewsWire", "Industry Pulse", "Market Daily", "Policy Watch", "Signal Desk"]
    sentiment_pool = ["POSITIVE", "NEUTRAL", "NEGATIVE"]
    for index in range(30):
        trend = trend_pool[index % len(trend_pool)]
        news_articles.append(
            {
                "id": f"news-{index + 1}",
                "title": f"{trend['title']}: update {index + 1}",
                "source": source_pool[index % len(source_pool)],
                "url": f"https://news.example/articles/{index + 1}",
                "published_at": iso_days_ago(index % 12),
                "industry": trend["industry"],
                "country": trend["country"],
                "category": trend["category"],
                "topic": trend["title"],
                "sentiment": sentiment_pool[index % len(sentiment_pool)],
                "relevance": 55 + (index * 2) % 40,
            }
        )

    competitors = [
        {
            "id": "comp-1",
            "name": "PlayArena",
            "domain": "playarena.example",
            "industry": "igaming",
            "categories": ["sports-betting", "online-casino"],
            "authority_score": 77,
            "content_focus": ["odds updates", "bonus guides", "regulation"],
        },
        {
            "id": "comp-2",
            "name": "BetSignal",
            "domain": "betsignal.example",
            "industry": "igaming",
            "categories": ["sports-betting", "esports"],
            "authority_score": 73,
            "content_focus": ["match previews", "betting tips", "promotions"],
        },
        {
            "id": "comp-3",
            "name": "CloudEdge",
            "domain": "cloudedge.example",
            "industry": "technology",
            "categories": ["cloud", "saas"],
            "authority_score": 81,
            "content_focus": ["cloud optimization", "platform reviews"],
        },
        {
            "id": "comp-4",
            "name": "EV Route",
            "domain": "evroute.example",
            "industry": "automotive",
            "categories": ["ev", "regulation"],
            "authority_score": 68,
            "content_focus": ["charging", "battery", "policy"],
        },
    ]

    publications = [
        {
            "id": "pub-1",
            "name": "Gaming Insights Daily",
            "domain": "gaminginsights.example",
            "industry": "igaming",
            "country": "United Kingdom",
            "category": "igaming",
            "authority_score": 72,
            "industry_relevance": 95,
            "audience": "Operators and affiliates",
            "backlink_potential": 78,
        },
        {
            "id": "pub-2",
            "name": "Regulatory Brief",
            "domain": "regulatorybrief.example",
            "industry": "igaming",
            "country": "Brazil",
            "category": "regulation",
            "authority_score": 79,
            "industry_relevance": 84,
            "audience": "Policy and compliance leaders",
            "backlink_potential": 71,
        },
        {
            "id": "pub-3",
            "name": "Tech Signal Weekly",
            "domain": "techsignal.example",
            "industry": "technology",
            "country": "United States",
            "category": "technology",
            "authority_score": 85,
            "industry_relevance": 92,
            "audience": "Founders and product teams",
            "backlink_potential": 80,
        },
        {
            "id": "pub-4",
            "name": "Auto Future Report",
            "domain": "autofuture.example",
            "industry": "automotive",
            "country": "Germany",
            "category": "automotive",
            "authority_score": 76,
            "industry_relevance": 88,
            "audience": "OEM and mobility teams",
            "backlink_potential": 69,
        },
    ]

    campaigns = [
        {
            "id": "campaign-1",
            "title": "The State of Brazil's Online Gambling Market",
            "industry": "igaming",
            "trend_id": "trend-brazil-gambling-regulation",
            "campaign_concept": "Data-driven analysis of regulation, consumer demand, and market readiness.",
            "seo_targets": ["brazil gambling regulation", "online gambling brazil", "brazil sports betting"],
            "pr_angle": "Market intelligence and compliance context for the new regulatory environment.",
            "publication_targets": ["Gaming Insights Daily", "Regulatory Brief"],
            "outreach_strategy": "Lead with a data point, then offer compliance commentary and local expert context.",
            "created_at": iso_days_ago(2),
            "updated_at": iso_days_ago(0),
        }
    ]

    return {
        "trends": trend_pool,
        "keywords": keywords,
        "newsArticles": news_articles,
        "competitors": competitors,
        "publications": publications,
        "campaigns": campaigns,
    }
